apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: wordsmith
    component: frontend
spec:
  type: NodePort  # Alternative au LoadBalancer pour les clusters locaux (minikube, kind, etc.)
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Port accessible depuis l'extérieur (30000-32767)
    protocol: TCP
    name: http
  selector:
    app: wordsmith
    component: frontend


