apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: wordsmith
    component: frontend
spec:
  type: LoadBalancer  # Pour exposer à l'extérieur du cluster
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: wordsmith
    component: frontend


