apiVersion: v1
kind: Service
metadata:
  name: words
  labels:
    app: wordsmith
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: wordsmith
    component: api


